### ISSUE TITLE
[Bug] TS definition for dispatch "setLoadingStatus" is incorrect

### ISSUE THREAD

**Issue by ValentinH** [paypal/react-paypal-js#112]
### 🐞 Describe the Bug

When following the documentation for "Defer loading" and implementing the example code in Typescript, I get a type error on the action value:
![image](https://user-images.githubusercontent.com/2678610/118107344-eae63880-b3de-11eb-9487-d0f2454c059a.png)

### 🔬 Minimal Reproduction

See this sandbox: https://codesandbox.io/s/react-paypal-serloadingstatus-mdkux?file=/src/Paypal.tsx

### 😕 Actual Behavior

Type error

### 🤔 Expected Behavior

"pending" should be accepted

### 🌍 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  | 6.0.0

**Comment by gregjopa** [comment]
Hi @ValentinH, thanks for letting us know about this bug. It's been fixed in #113 and included in the 6.0.1 release.

**Comment by HasanMothaffar** [comment]
It seems that the error isn't fixed? I can reproduce the original TS error in version `7.8.1`.

## Steps to reproduce

1. Open the sandbox of the original poster: https://codesandbox.io/s/react-paypal-serloadingstatus-mdkux?file=/src/Paypal.tsx
2. Bump the version of the `react-paypal-js` package to version `7.8.1`

Here's a picture of the error:

![image](https://user-images.githubusercontent.com/60794869/183115989-54ce026a-18d1-481d-912a-c432e4d03266.png)

As a workaround, I managed to do this:

```ts
import { SCRIPT_LOADING_STATE } from "@paypal/react-paypal-js";

dispatch({
    type: "setLoadingStatus",
    value: SCRIPT_LOADING_STATE.PENDING,
});
```
