### ISSUE TITLE
 [BUG] RESOURCE_NOT_FOUND 

### ISSUE THREAD

**Issue by devchristina** [paypal/react-paypal-js#385]
I'm getting this as well even, I'm not new but then this started to pop out, also seems to be the direct cause for the following errors that break my app completely:

```
smart_api_billagmt_subscriptions_get_contingency_error 
Object { timestamp: "1692414277583", referer: "www.sandbox.paypal.com", sdkCorrelationID: "f29334927a890", sessionID: "uid_b6e3970e67_mdm6mdm6ntg", clientID: "AT_JzFs8g...", env: "sandbox", buttonSessionID: "uid_f07437e2c9_mdm6mdm6ntg", buttonCorrelationID: "f368299bd965a", token: "0BL308..." }

```

Then

```
Uncaught Error: RESOURCE_NOT_FOUND
js:3:71880

at error https://www.paypal.com/sdk/js?client-id=AT_JzFs8gVW...&intent=subscription&vault=true:3
at  Wr https://www.paypal.com/sdk/js?client-id=AT_JzFs8gVW...&intent=subscription&vault=true:3
at [...]
```

_Originally posted by @GatoVuelta in https://github.com/paypal/react-paypal-js/issues/374#issuecomment-1684723567_

**Comment by ravishekhar** [comment]
This issue is fixed. Thanks for your patience.

**Comment by dundja** [comment]
@ravishekhar @devchristina I am still experiencing `RESOURCE_NOT_FOUND` issue. Will you guys release fix and publish new package version or is there anything else i need to do in order to resolve this problem ?

**Comment by devchristina** [comment]
@dundja -- Ack

**Comment by dundja** [comment]
@devchristina any news on this one ?

**Comment by devchristina** [comment]
@dundja -- Checked in with our product & eng team. They're unable to reproduce this issue with the Live flow. Can you tell me more details, e.g. 

- Which environment are you in?
- Are you using the same app that you were using previously or are you using a new app? 
- Can you provide the PayPal-Debug-ID when you see this error happen? _This can be found by going into the developer tools of the browser and looking at the response from the server,_

**Comment by dundja** [comment]
@devchristina 
- Which environment are you in?
   - I am on **sandbox** env. 
- Are you using the same app that you were using previously or are you using a new app?
   - Same app, just new plans that I created. I tried with new app as well but same issue.
- Can you provide the PayPal-Debug-ID when you see this error happen?
   - Regarding the debug ID, i don't see any. Request that is failing to me is `https://www.sandbox.paypal.com/smart/api/billagmt/subscriptions/{SUBSCRIPTION_ID}`, returning status 400 with following response:
```
ack: "contingency"
contingency: "RESOURCE_NOT_FOUND"
meta: {calc: STRING, rlog: STRING}
server: SERVER_ID
```
I am using latest version of the package `"@paypal/react-paypal-js": "^8.1.3"`.
Could it be that subscription is created with `https://www.sandbox.paypal.com/v1/billing/subscriptions` while once you try to get `billagmt` (which I saw somewhere that it is legacy?) , you are using `https://www.sandbox.paypal.com/smart/api/billagmt/subscriptions/{SUBSCRIPTION_ID}` ?

Code that i am using is simple:
```
<PayPalButtons
              createSubscription={createSubscription}
              onApprove={onApprove}
              onError={onError}
              style={{
                edges: 'rounded',
                color: 'blue',
                layout: 'vertical',
                label: 'subscribe',
              }}
            />
```
Seams like subscription is created, `plan_id` is ok (on my business sandbox account there is subscription plan with that `plan_id`), but when it tries to reach out to that subscription id on that endpoint, it fails.

**Comment by dundja** [comment]
@devchristina Just to confirm that I also tried with `"@paypal/paypal-js": "^7.0.3"` package (since I saw that it is newer version that `react-paypal-js` is using) and result is the same error, `status 400` on `https://www.sandbox.paypal.com/smart/api/billagmt/subscriptions/{SUBSCRIPTION_ID}` endpoint.
cc @gregjopa

**Comment by ravishekhar** [comment]
@dundja can you please confirm if you are facing this issue on Sandbox environment or Prod? Also please share a debug id. 
The debug id will be available as a Response Header `Paypal-Debug-Id`
You can find it under "Response Headers" section on the network tab of browser dev tools.

**Comment by dundja** [comment]
@devchristina @ravishekhar Today I tried but now i got same issue as #393

**Comment by F-Moody** [comment]
Same here, all our users are impacted since all the subscriptions button are not calling the `onApprove` callback after the payment has been collected
